### ISSUE TITLE
Swagger Definitions for RSVP APIs

### ISSUE THREAD

**Issue by justinyoo** [TeamKDA/KorDevAus#35]
for #30 #31 

And Azure Functions proxy for #29

**Comment by justinyoo** [comment]
https://github.com/TeamKDA/KorDevAus-RSVP-API/blob/master/swagger.yaml

@alxpark Let's do code review

**Comment by justinyoo** [comment]
마스터에 직접 붙어서 하는 지라 이렇게 필요한 부분 퍼머링크 붙이면 될 걸요?

https://github.com/TeamKDA/KorDevAus-RSVP-API/blob/afaec0e58552ff42985e8d8a3d6cf979f79035d4/swagger.yaml#L12

**Comment by alxpark** [comment]
이 swagger 스펙을 swagger ui에 넣어서 볼수 있을까요? swagger를 잘 몰라서 생짜 코드를 볼고 리뷰하기 좀 힘드네요. 스펙에 맞는지는 ui에 넣어보면 validation도 해주고 모델로 보여주니 이해하기 쉬울듯 합니다.

**Comment by justinyoo** [comment]
@alxpark https://editor.swagger.io/ 여기에서 불러와서 보시면 대요. 밸리데이션은 통과했으니 API request/response 구조가 말이 되는지만 확인하시면 될 듯 싶습니다.

**Comment by justinyoo** [comment]
Done
