### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by justinyoo** [TeamKDA/KorDevAus#38]
For announcement and RSVP, we need database schema

**Comment by justinyoo** [comment]
First draft: https://1drv.ms/u/s!ArWHNGHxF7lBgoRqIBJu3AokTyQCJA

Open it on https://draw.io

**Comment by justinyoo** [comment]
@alxpark 리뷰 함 가시지요!

**Comment by alxpark** [comment]
@justinyoo 훌륭합니다! 💯 
몇가지 생각나는건 (optional)
- Event테이블에 max인원을 기능?
- Location보다 Venue어떠세요?
- DateCreated보다 CreatedDate? 왜냐하면 CreatedBy랑 같은 패턴이면 좋을듯. Updated도..
이상임다!

**Comment by justinyoo** [comment]
앗 고맙습니다.

* MaxAttendees 빠졌네요! 그러면서 자연스레 Waitlist 테이블 추가하겠습니다.
* Venue 단어가 생각이 안나서 ㅠ 바꾸겠습니다!
* Date (when the recored was) Created, (Recored was) Created By 라서 저렇게 했스빈다.

**Comment by justinyoo** [comment]
계속 조금씩 작업 중입니다!

**Comment by justinyoo** [comment]
Done
